config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  root 'homes#top'
  get '/home/about' => 'homes#about', as: "about"

  resources :books
  resources :users

  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @booknew = Book.new
    @books = Book.all
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
  end

  def create
    @booknew = Book.new(book_params)
    @booknew.user_id = current_user.id
    if @booknew.save
      flash[:notice] = "ok"
      redirect_to books_path
    else
      flash[:notice] = "ng"
    end
  end

  def update
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @booknew = Book.new
    @books = @user.books
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div class="containaer">
  <div class="row">
    <div class="col-md-3">
      <div class="col">
        <%= render 'layouts/userinfo', user: current_user %>
      </div>
      <div class="col">
        <%= render 'layouts/newbook', book: @booknew %>
      </div>
    </div>
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>body</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="containaer">
  <div class="row">
    <div class="col-md-3">
      <div class="col">
        <%= render 'layouts/userinfo', user: @user %>
      </div>
      <div class="col">
        <%= render 'layouts/newbook', book: @booknew %>
      </div>
    </div>
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>body</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %><br />
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class:"navbar-brand" do %>Bookers<% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <%= link_to user_path(current_user), class:"nav-link" do %>Home<% end %>
        <%= link_to users_path, class:"nav-link" do %>Users<% end %>
        <%= link_to books_path, class:"nav-link" do %>Books<% end %>
        <%= link_to destroy_user_session_path, method: :delete, class:"nav-link" do %>Log_out<% end %>
      <% else %>
        <%= link_to root_path, class:"nav-link" do %>Home<% end %>
        <%= link_to about_path, class:"nav-link" do %>About<% end %>
        <%= link_to new_user_registration_path, class:"nav-link" do %>Sign_up<% end %>
        <%= link_to user_session_path, class:"nav-link" do %>Sign_in<% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_newbook.html.erb
<%= form_with model:book do |f| %>
  <p>title</p>
  <%= f.text_field :title %>
  <p>body</p>
  <%= f.text_area :body %><br />
  <%= f.submit "送信" %>
<% end %>

app/views/layouts/_userinfo.html.erb
<%= image_tag user.get_profile_image(100,100) %>
<table>
  <thead>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>説明</td>
      <td><%= user.introduction %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="containaer">
  <div class="row">
    <div class="col-md-3">
      <div class="col">
        <%= render 'layouts/userinfo', user: current_user %>
      </div>
      <div class="col">
        <%= render 'layouts/newbook', book: @booknew %>
      </div>
    </div>
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>body</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to user_path(user) do %>show<% end %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>

app/views/users/show.html.erb
<div class="containaer">
  <div class="row">
    <div class="col-md-3">
      <div class="col">
        <%= render 'layouts/userinfo', user: @user %>
      </div>
      <div class="col">
        <%= render 'layouts/newbook', book: @booknew %>
      </div>
    </div>
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>body</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= image_tag book.user.get_profile_image(100,100) %></td>
            <td><%= link_to book_path(book) do %><%= book.title %><% end %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>